image: node:10

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test
  - deploy

before_script:
  - cd server

build:
  stage: build
  tags:
    - docker
  script:
    - npm install

test:
  stage: test
  tags:
    - docker
  services:
    - mongo:4.1
  variables:
    MONGODB_URI: "mongodb://mongo:27017/animals-test"
  script:
    - npm test

deploy:
  stage: deploy
  tags:
    - docker
  script:
  - echo "Deploy master to production"
  only:
  - master
